name: Build Thetis

on:
  # Push to master or PR
  push:
    branches:
      - master
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Scheduled build at 0230 UTC on Monday mornings to detect bitrot.
    - cron:  '30 2 * * 1'

jobs:
  build:
    name: "Build Thetis"
    # The type of runner that the job will run on
    runs-on: self-hosted
    # The docker container to use.
    container:
      # UNDO ME
      # image: firedrakeproject/firedrake-vanilla-default:latest
      image: firedrakeproject/firedrake-vanilla-default:pip
    steps:
      - name: Pre-cleanup
        run: |
          : # Wipe everything away in the current directory
          find . -delete

      - uses: actions/checkout@v4
        with:
          path: thetis-repo

      - name: Install Thetis
        id: install
        run: |
          : # Pass '--system-site-packages' so Firedrake can be found
          python3 -m venv --system-site-packages venv-thetis
          . venv-thetis/bin/activate
          pip install ./thetis-repo
          pip list

      - name: Lint
        run: |
          . venv-thetis/bin/activate
          pip install flake8
          make -C thetis-repo lint

      - name: Test Thetis
        # Run even if the step above failed
        if: success() || steps.install.conclusion == 'success'
        run: |
          firedrake-clean
          . venv-thetis/bin/activate
          : # Run the serial tests
          : # Use pytest-xdist here so we can have a single collated output (not possible
          : # for parallel tests)
          firedrake-run-split-tests 1 1 -n 12 --verbose thetis-repo/test
          : # Run the parallel tests
          firedrake-run-split-tests 2 6 --verbose thetis-repo/test

      - name: Test Thetis adjoint
        if: success() || steps.install.conclusion == 'success'
        run: |
          firedrake-clean
          . venv-thetis/bin/activate
          firedrake-run-split-tests 1 1 -n 12 --verbose thetis-repo/test_adjoint

      - name: Post-cleanup
        if: always()
        run: |
          find . -delete
          firedrake-clean
